#ifndef BEAM_MODULES_PRELUDE_HPP
#define BEAM_MODULES_PRELUDE_HPP
#include <algorithm>
#include <array>
#include <atomic>
#include <cctype>
#include <charconv>
#include <chrono>
#include <concepts>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <exception>
#include <filesystem>
#include <fstream>
#include <functional>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <ostream>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>
#include <boost/algorithm/string.hpp>
#include <boost/asio/ip/tcp.hpp>
#include <boost/atomic/atomic.hpp>
#include <boost/circular_buffer.hpp>
#include <boost/chrono/system_clocks.hpp>
#include <boost/date_time/c_local_time_adjustor.hpp>
#include <boost/date_time/gregorian/gregorian_types.hpp>
#include <boost/date_time/local_time/local_time.hpp>
#include <boost/date_time/local_time_adjustor.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/date_time/posix_time/posix_time_duration.hpp>
#include <boost/date_time/posix_time/posix_time_types.hpp>
#include <boost/date_time/posix_time/ptime.hpp>
#include <boost/endian.hpp>
#include <boost/endian/conversion.hpp>
#include <boost/functional/factory.hpp>
#include <boost/iostreams/categories.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/multiprecision/cpp_dec_float.hpp>
#include <boost/optional.hpp>
#include <boost/optional/optional.hpp>
#include <boost/rational.hpp>
#include <boost/range/adaptor/map.hpp>
#include <boost/range/adaptor/reversed.hpp>
#include <boost/range/iterator_range.hpp>
#include <boost/signals2.hpp>
#include <boost/thread/condition_variable.hpp>
#include <boost/thread/locks.hpp>
#include <boost/thread/mutex.hpp>
#include <boost/throw_exception.hpp>
#include <boost/uuid/string_generator.hpp>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <cryptopp/osrng.h>
#include <cryptopp/sha.h>
#include <doctest/doctest.h>
#include <Viper/CommitStatement.hpp>
#include <Viper/Conversions.hpp>
#include <Viper/CreateTableStatement.hpp>
#include <Viper/DataTypes/NativeToDataType.hpp>
#include <Viper/DeleteStatement.hpp>
#include <Viper/ExecuteException.hpp>
#include <Viper/Expressions/Expression.hpp>
#include <Viper/Expressions/SqlFunctions.hpp>
#include <Viper/InsertRangeStatement.hpp>
#include <Viper/RollbackStatement.hpp>
#include <Viper/Row.hpp>
#include <Viper/SelectStatement.hpp>
#include <Viper/StartTransactionStatement.hpp>
#include <Viper/UpdateStatement.hpp>
#include <Viper/UpsertStatement.hpp>
#include <Viper/Viper.hpp>
#include <zlib.h>
#include "Beam/Codecs/Decoder.hpp"
#include "Beam/Codecs/Encoder.hpp"
#include "Beam/Collections/Enum.hpp"
#include "Beam/IO/Buffer.hpp"
#include "Beam/IO/BufferReader.hpp"
#include "Beam/IO/Channel.hpp"
#include "Beam/IO/ConnectException.hpp"
#include "Beam/IO/Connection.hpp"
#include "Beam/IO/EndOfFileException.hpp"
#include "Beam/IO/IOException.hpp"
#include "Beam/IO/PipedReader.hpp"
#include "Beam/IO/PipedWriter.hpp"
#include "Beam/IO/Reader.hpp"
#include "Beam/IO/Writer.hpp"
#include "Beam/Network/IpAddress.hpp"
#include "Beam/Network/SocketException.hpp"
#include "Beam/Network/SocketIdentifier.hpp"
#include "Beam/Parsers/Parse.hpp"
#include "Beam/Pointers/LocalPointerPolicy.hpp"
#include "Beam/Pointers/Out.hpp"
#include "Beam/Pointers/Ref.hpp"
#include "Beam/Routines/RoutineHandlerGroup.hpp"
#include "Beam/ServiceLocator/DirectoryEntry.hpp"
#include "Beam/Sql/Conversions.hpp"
#include "Beam/Sql/PosixTimeToSqlDateTime.hpp"
#include "Beam/Utilities/Algorithm.hpp"
#include "Beam/Utilities/ReportException.hpp"
#include "Beam/IO/OpenState.hpp"
#include "Beam/IO/SharedBuffer.hpp"
#include "Beam/Pointers/Dereference.hpp"
#include "Beam/Pointers/LocalPtr.hpp"
#include "Beam/Pointers/VirtualPtr.hpp"
#include "Beam/Queries/Sequence.hpp"
#include "Beam/Queues/AbstractQueue.hpp"
#include "Beam/Queues/BaseQueue.hpp"
#include "Beam/Queues/CallbackQueue.hpp"
#include "Beam/Queues/PipeBrokenException.hpp"
#include "Beam/Queues/Publisher.hpp"
#include "Beam/Queues/Queue.hpp"
#include "Beam/Queues/QueueWriter.hpp"
#include "Beam/Queues/QueueWriterPublisher.hpp"
#include "Beam/Queues/RoutineTaskQueue.hpp"
#include "Beam/Queues/ScopedQueueWriter.hpp"
#include "Beam/Routines/Routine.hpp"
#include "Beam/Routines/RoutineHandler.hpp"
#include "Beam/Serialization/ReceiverMixin.hpp"
#include "Beam/Serialization/SenderMixin.hpp"
#include "Beam/Serialization/BinaryReceiver.hpp"
#include "Beam/Serialization/BinarySender.hpp"
#include "Beam/Serialization/DataShuttle.hpp"
#include "Beam/Serialization/Receiver.hpp"
#include "Beam/Serialization/Sender.hpp"
#include "Beam/Serialization/SerializedValue.hpp"
#include "Beam/Services/RecordMessage.hpp"
#include "Beam/Services/Service.hpp"
#include "Beam/Services/ServiceProtocolClient.hpp"
#include "Beam/Services/ServiceProtocolClientBuilder.hpp"
#include "Beam/Threading/ConditionVariable.hpp"
#include "Beam/Threading/LockRelease.hpp"
#include "Beam/Threading/Mutex.hpp"
#include "Beam/Threading/RecursiveMutex.hpp"
#include "Beam/Threading/Sync.hpp"
#include "Beam/Threading/ThreadPool.hpp"
#include "Beam/TimeService/Timer.hpp"
#include "Beam/Utilities/TypeTraits.hpp"
#include "Beam/Codecs/DecoderException.hpp"
#include "Beam/Codecs/EncoderException.hpp"
#include "Beam/Codecs/NullDecoder.hpp"
#include "Beam/Codecs/NullEncoder.hpp"
#include "Beam/Network/NetworkDetails.hpp"
#include "Beam/Queues/QueueReader.hpp"
#include "Beam/Routines/Async.hpp"
#include "Beam/Serialization/ShuttleDateTime.hpp"
#include "Beam/Utilities/FixedString.hpp"
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/algorithm/string/trim.hpp>
#include <boost/asio/ip/multicast.hpp>
#include <boost/asio/ip/udp.hpp>
#include <boost/asio/ip/unicast.hpp>
#include <boost/asio/write.hpp>
#include <openssl/ssl.h>
#include "Beam/Serialization/ShuttleUniquePtr.hpp"
#include "Beam/Serialization/ShuttleVector.hpp"
#include "Beam/Serialization/TypeRegistry.hpp"
#include "Beam/Threading/TaskRunner.hpp"
#include "Beam/Utilities/HashTuple.hpp"
#include <Viper/Expressions/Expressions.hpp>
#include "Beam/Json/JsonParser.hpp"
#include "Beam/Network/TcpSocketOptions.hpp"
#include "Beam/Serialization/SerializationException.hpp"
#include "Beam/ServiceLocator/ServiceEntry.hpp"
#include "Beam/Services/ServiceRequestException.hpp"
#include "Beam/Utilities/BeamWorkaround.hpp"
#include <boost/asio/ip/address.hpp>
#include <boost/asio/steady_timer.hpp>
#include <cassert>
#include "Beam/IO/ChannelIdentifier.hpp"
#include "Beam/Pointers/NativePointerPolicy.hpp"
#include "Beam/Services/NullSession.hpp"
#include "Beam/Services/ServiceSlots.hpp"
#include "Beam/Serialization/ShuttleOptional.hpp"
#include <boost/date_time/gregorian/gregorian.hpp>
#include <boost/iterator/counting_iterator.hpp>
#include <boost/iterator/transform_iterator.hpp>
#include <boost/iterator/zip_iterator.hpp>
#include <boost/tuple/tuple.hpp>
#include <boost/iterator/iterator_facade.hpp>
#include <boost/callable_traits.hpp>
#include <boost/mp11.hpp>
#include <boost/variant/variant.hpp>
#include "Beam/IO/SuffixBuffer.hpp"
#include "Beam/ServiceLocator/Permissions.hpp"
#include "Beam/Utilities/Bcrypt.hpp"
#include <boost/callable_traits/return_type.hpp>
#include <typeindex>
#include "Beam/Serialization/ShuttleVariant.hpp"
#include "Beam/Utilities/HashPosixTimeTypes.hpp"
#include <boost/date_time/posix_time/posix_time_io.hpp>
#include <boost/functional/hash.hpp>
#include <boost/system/system_error.hpp>
#include <boost/variant.hpp>
#include "Beam/Json/JsonObject.hpp"
#include "Beam/Serialization/ShuttleBitset.hpp"
#include "Beam/Serialization/ShuttleSharedPtr.hpp"
#include "Beam/Serialization/TypeEntry.hpp"
#include "Beam/ServiceLocator/AccountUpdate.hpp"
#include "Beam/Utilities/DllExport.hpp"
#include "Beam/Utilities/Singleton.hpp"
#include "Beam/Utilities/Streamable.hpp"
#include <boost/asio/io_context.hpp>
#include <boost/thread/thread.hpp>
#include <cryptopp/hex.h>
#ifdef DELETE
  #undef DELETE
#endif
#endif
