#ifndef BEAM_MODULES_PRELUDE_HPP
#define BEAM_MODULES_PRELUDE_HPP
#include <algorithm>
#include <array>
#include <atomic>
#include <cctype>
#include <concepts>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <exception>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <limits>
#include <memory>
#include <random>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>
#include <boost/algorithm/string.hpp>
#include <boost/date_time/posix_time/posix_time_duration.hpp>
#include <boost/date_time/posix_time/posix_time_types.hpp>
#include <boost/date_time/posix_time/ptime.hpp>
#include <boost/endian/conversion.hpp>
#include <boost/functional/factory.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/optional/optional.hpp>
#include <boost/range/adaptor/map.hpp>
#include <boost/signals2.hpp>
#include <boost/thread/locks.hpp>
#include <boost/thread/mutex.hpp>
#include <boost/throw_exception.hpp>
#include <cryptopp/osrng.h>
#include <cryptopp/sha.h>
#include <Viper/Viper.hpp>
#include <zlib.h>
#include "Beam/Collections/Enum.hpp"
#include "Beam/Collections/SynchronizedList.hpp"
#include "Beam/Collections/SynchronizedMap.hpp"
#include "Beam/Collections/SynchronizedSet.hpp"
#include "Beam/IO/Buffer.hpp"
#include "Beam/IO/BufferOutputStream.hpp"
#include "Beam/IO/BufferReader.hpp"
#include "Beam/IO/Channel.hpp"
#include "Beam/IO/ConnectException.hpp"
#include "Beam/IO/Connection.hpp"
#include "Beam/IO/EndOfFileException.hpp"
#include "Beam/IO/IOException.hpp"
#include "Beam/IO/Reader.hpp"
#include "Beam/IO/ServerConnection.hpp"
#include "Beam/IO/Writer.hpp"
#include "Beam/Network/IpAddress.hpp"
#include "Beam/Network/SecureSocketChannel.hpp"
#include "Beam/Network/TcpSocketChannel.hpp"
#include "Beam/Pointers/LocalPointerPolicy.hpp"
#include "Beam/Pointers/Out.hpp"
#include "Beam/Pointers/Ref.hpp"
#include "Beam/Routines/RoutineHandlerGroup.hpp"
#include "Beam/Serialization/JsonReceiver.hpp"
#include "Beam/Serialization/JsonSender.hpp"
#include "Beam/Serialization/ShuttleAtomic.hpp"
#include "Beam/ServiceLocator/DirectoryEntry.hpp"
#include "Beam/ServiceLocator/SessionEncryption.hpp"
#include "Beam/Sql/Conversions.hpp"
#include "Beam/Sql/DatabaseConnectionPool.hpp"
#include "Beam/Sql/PosixTimeToSqlDateTime.hpp"
#include "Beam/Utilities/Algorithm.hpp"
#include "Beam/Utilities/Casts.hpp"
#include "Beam/Utilities/ReportException.hpp"
#include "Beam/IO/LocalClientChannel.hpp"
#include "Beam/IO/LocalServerConnection.hpp"
#include "Beam/IO/OpenState.hpp"
#include "Beam/IO/SharedBuffer.hpp"
#include "Beam/Pointers/Dereference.hpp"
#include "Beam/Pointers/LocalPtr.hpp"
#include "Beam/Pointers/VirtualPtr.hpp"
#include "Beam/Queries/AndExpression.hpp"
#include "Beam/Queries/BasicQuery.hpp"
#include "Beam/Queries/CachedDataStoreEntry.hpp"
#include "Beam/Queries/ConstantExpression.hpp"
#include "Beam/Queries/Evaluator.hpp"
#include "Beam/Queries/EvaluatorNode.hpp"
#include "Beam/Queries/ExpressionSubscriptions.hpp"
#include "Beam/Queries/ExpressionVisitor.hpp"
#include "Beam/Queries/FunctionEvaluatorNode.hpp"
#include "Beam/Queries/FunctionExpression.hpp"
#include "Beam/Queries/GlobalVariableDeclarationExpression.hpp"
#include "Beam/Queries/IndexedValue.hpp"
#include "Beam/Queries/LocalDataStore.hpp"
#include "Beam/Queries/MemberAccessExpression.hpp"
#include "Beam/Queries/NotExpression.hpp"
#include "Beam/Queries/OrExpression.hpp"
#include "Beam/Queries/ParameterExpression.hpp"
#include "Beam/Queries/Range.hpp"
#include "Beam/Queries/ReduceExpression.hpp"
#include "Beam/Queries/Sequence.hpp"
#include "Beam/Queries/SequencedValue.hpp"
#include "Beam/Queries/SequencedValuePublisher.hpp"
#include "Beam/Queries/SessionCachedDataStoreEntry.hpp"
#include "Beam/Queries/SetVariableExpression.hpp"
#include "Beam/Queries/SqlTranslator.hpp"
#include "Beam/Queries/SqlUtilities.hpp"
#include "Beam/Queries/Subscriptions.hpp"
#include "Beam/Queries/VariableExpression.hpp"
#include "Beam/Queues/ConverterQueueWriter.hpp"
#include "Beam/Queues/MultiQueueWriter.hpp"
#include "Beam/Queues/Publisher.hpp"
#include "Beam/Queues/Queue.hpp"
#include "Beam/Queues/RoutineTaskQueue.hpp"
#include "Beam/Queues/ScopedQueueReader.hpp"
#include "Beam/Routines/RoutineHandler.hpp"
#include "Beam/Serialization/BinaryReceiver.hpp"
#include "Beam/Serialization/BinarySender.hpp"
#include "Beam/Serialization/DataShuttle.hpp"
#include "Beam/Serialization/Receiver.hpp"
#include "Beam/Serialization/Sender.hpp"
#include "Beam/Services/RecordMessage.hpp"
#include "Beam/Services/Service.hpp"
#include "Beam/Services/ServiceProtocolClient.hpp"
#include "Beam/Services/ServiceProtocolClientBuilder.hpp"
#include "Beam/Services/ServiceProtocolClientHandler.hpp"
#include "Beam/Services/ServiceProtocolServlet.hpp"
#include "Beam/Services/ServiceProtocolServletContainer.hpp"
#include "Beam/Threading/ConditionVariable.hpp"
#include "Beam/Threading/Mutex.hpp"
#include "Beam/Threading/RecursiveMutex.hpp"
#include "Beam/Threading/Sync.hpp"
#include "Beam/TimeService/LocalTimeClient.hpp"
#include "Beam/TimeService/TimeClient.hpp"
#include "Beam/TimeService/Timer.hpp"
#include "Beam/TimeService/TriggerTimer.hpp"
#include "Beam/Utilities/SharedCallable.hpp"
#include "Beam/Utilities/TypeTraits.hpp"
#ifdef DELETE
  #undef DELETE
#endif
#endif
