set(outputs "@clean_outputs@")
if("@CMAKE_GENERATOR@" MATCHES "^Visual Studio ")
  set(tracking_directories "@clean_tracking_directories@")
  string(TOLOWER "@PROJECT_BINARY_DIR@" build_directory)
  foreach(directory IN LISTS tracking_directories)
    file(GLOB logs "${directory}/*.tlog/*.write.*.tlog"
      "${directory}/*.tlog/*.secondary.*.tlog")
    foreach(log IN LISTS logs)
      file(STRINGS "${log}" entries)
      foreach(entry IN LISTS entries)
        if(IS_ABSOLUTE "${entry}")
          file(TO_CMAKE_PATH "${entry}" output)
          string(TOLOWER "${output}" normalized_output)
          cmake_path(IS_PREFIX build_directory "${normalized_output}"
            NORMALIZE is_build_output)
          if(is_build_output)
            list(APPEND outputs "${output}")
          endif()
        endif()
      endforeach()
    endforeach()
  endforeach()
else()
  execute_process(COMMAND "@CMAKE_COMMAND@" --build "@PROJECT_BINARY_DIR@"
    --config "$<CONFIG>" --target clean RESULT_VARIABLE clean_result)
  if(NOT clean_result EQUAL 0)
    message(FATAL_ERROR "Failed to clean $<CONFIG>.")
  endif()
endif()
list(FILTER outputs EXCLUDE REGEX "^$")
list(REMOVE_DUPLICATES outputs)
file(REAL_PATH "@PROJECT_BINARY_DIR@" build_directory)
foreach(output IN LISTS outputs)
  set(comparison_directory "${build_directory}")
  set(comparison_output "${output}")
  if(CMAKE_HOST_WIN32)
    string(TOLOWER "${comparison_directory}" comparison_directory)
    string(TOLOWER "${comparison_output}" comparison_output)
  endif()
  cmake_path(IS_PREFIX comparison_directory "${comparison_output}"
    NORMALIZE is_build_output)
  if(NOT is_build_output OR IS_DIRECTORY "${output}")
    message(FATAL_ERROR "Invalid build output: ${output}")
  endif()
endforeach()
file(REMOVE ${outputs})
foreach(output IN LISTS outputs)
  if(EXISTS "${output}" OR IS_SYMLINK "${output}")
    message(FATAL_ERROR "Failed to remove ${output}.")
  endif()
endforeach()
