file(REAL_PATH "@PROJECT_BINARY_DIR@" build_directory)
if(CMAKE_HOST_WIN32)
  string(TOLOWER "${build_directory}" build_directory)
endif()

function(is_build_output output result)
  cmake_path(GET output PARENT_PATH directory)
  file(REAL_PATH "${directory}" directory)
  cmake_path(GET output FILENAME filename)
  set(path "${directory}/${filename}")
  if(CMAKE_HOST_WIN32)
    string(TOLOWER "${path}" path)
  endif()
  cmake_path(IS_PREFIX build_directory "${path}" NORMALIZE is_output)
  set(${result} ${is_output} PARENT_SCOPE)
endfunction()

set(outputs "@clean_outputs@")
if("@CMAKE_GENERATOR@" MATCHES "^Visual Studio ")
  set(tracking_directories "@clean_tracking_directories@")
  foreach(directory IN LISTS tracking_directories)
    file(GLOB logs "${directory}/*.tlog/*.write.*.tlog"
      "${directory}/*.tlog/*.secondary.*.tlog")
    foreach(log IN LISTS logs)
      file(STRINGS "${log}" entries)
      foreach(entry IN LISTS entries)
        if(IS_ABSOLUTE "${entry}" AND
            (EXISTS "${entry}" OR IS_SYMLINK "${entry}"))
          file(TO_CMAKE_PATH "${entry}" output)
          is_build_output("${output}" is_output)
          if(is_output)
            list(APPEND outputs "${output}")
          endif()
        endif()
      endforeach()
    endforeach()
  endforeach()
else()
  execute_process(COMMAND "@CMAKE_COMMAND@" --build "@PROJECT_BINARY_DIR@"
    --config "$<CONFIG>" --target clean RESULT_VARIABLE clean_result)
  if(NOT clean_result EQUAL 0)
    message(FATAL_ERROR "Failed to clean $<CONFIG>.")
  endif()
endif()
list(FILTER outputs EXCLUDE REGEX "^$")
list(REMOVE_DUPLICATES outputs)
foreach(output IN LISTS outputs)
  if(NOT EXISTS "${output}" AND NOT IS_SYMLINK "${output}")
    continue()
  endif()
  is_build_output("${output}" is_output)
  if(NOT is_output OR IS_DIRECTORY "${output}")
    message(FATAL_ERROR "Invalid build output: ${output}")
  endif()
endforeach()
file(REMOVE ${outputs})
foreach(output IN LISTS outputs)
  if(EXISTS "${output}" OR IS_SYMLINK "${output}")
    message(FATAL_ERROR "Failed to remove ${output}.")
  endif()
endforeach()
