file(REAL_PATH "@PROJECT_BINARY_DIR@" build_directory)
if(CMAKE_HOST_WIN32)
  string(TOLOWER "${build_directory}" build_directory)
endif()

function(is_build_output output result)
  cmake_path(GET output PARENT_PATH directory)
  file(REAL_PATH "${directory}" directory)
  cmake_path(GET output FILENAME filename)
  set(path "${directory}/${filename}")
  if(CMAKE_HOST_WIN32)
    string(TOLOWER "${path}" path)
  endif()
  cmake_path(IS_PREFIX build_directory "${path}" NORMALIZE is_output)
  set(${result} ${is_output} PARENT_SCOPE)
endfunction()

set(outputs "@clean_outputs@")
set(arguments)
if("@CMAKE_GENERATOR@" MATCHES "^Visual Studio ")
  set(arguments -- /nologo /p:ExtensionsToDeleteOnClean=__no_files__)
endif()
execute_process(COMMAND "@CMAKE_COMMAND@" --build "@PROJECT_BINARY_DIR@"
  --config "$<CONFIG>" --target clean ${arguments}
  RESULT_VARIABLE clean_result OUTPUT_VARIABLE clean_output
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT clean_output STREQUAL "")
  message("${clean_output}")
endif()
if(NOT clean_result EQUAL 0)
  message(FATAL_ERROR "Failed to clean $<CONFIG>.")
endif()
list(FILTER outputs EXCLUDE REGEX "^$")
list(REMOVE_DUPLICATES outputs)
foreach(output IN LISTS outputs)
  if(NOT EXISTS "${output}" AND NOT IS_SYMLINK "${output}")
    continue()
  endif()
  is_build_output("${output}" is_output)
  if(NOT is_output OR IS_DIRECTORY "${output}")
    message(FATAL_ERROR "Invalid build output: ${output}")
  endif()
endforeach()
file(REMOVE ${outputs})
foreach(output IN LISTS outputs)
  if(EXISTS "${output}" OR IS_SYMLINK "${output}")
    message(FATAL_ERROR "Failed to remove ${output}.")
  endif()
endforeach()
