if(WIN32)
  include("${CMAKE_CURRENT_LIST_DIR}/dependencies.windows.cmake")
else()
  include("${CMAKE_CURRENT_LIST_DIR}/dependencies.posix.cmake")
endif()
set(ASPEN_INCLUDE_PATH "${PROJECT_BINARY_DIR}/Dependencies/aspen/Include")
set(BEAM_INCLUDE_PATH "${CMAKE_CURRENT_LIST_DIR}/../Include")
set(BEAM_SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/../Source")
set(DOCTEST_INCLUDE_PATH "${PROJECT_BINARY_DIR}/Dependencies/doctest-2.3.4")
set(PYBIND11_INCLUDE_PATH
  "${PROJECT_BINARY_DIR}/Dependencies/pybind11-2.2.4/include")
set(TCLAP_INCLUDE_PATH "${PROJECT_BINARY_DIR}/Dependencies/tclap-1.2.1/include")
set(VIPER_INCLUDE_PATH "${PROJECT_BINARY_DIR}/Dependencies/viper/Include")
