cmake_minimum_required(VERSION 3.28)
if(NOT IS_DIRECTORY "${BUILD_DIRECTORY}")
  message(FATAL_ERROR "Invalid build directory: ${BUILD_DIRECTORY}")
endif()
file(REAL_PATH "${BUILD_DIRECTORY}" build_directory)
if(NOT DEFINED SOURCE_DIRECTORY)
  set(SOURCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/..")
endif()
file(REAL_PATH "${SOURCE_DIRECTORY}" source_directory)
cmake_path(GET build_directory PARENT_PATH parent_directory)
set(comparison_directory "${build_directory}")
if(CMAKE_HOST_WIN32)
  string(TOLOWER "${comparison_directory}" comparison_directory)
  string(TOLOWER "${source_directory}" source_directory)
endif()
cmake_path(IS_PREFIX comparison_directory "${source_directory}"
  NORMALIZE contains_source)
if(contains_source OR build_directory STREQUAL parent_directory)
  message(FATAL_ERROR "Cannot reset the source directory or its ancestors.")
endif()
set(forwarding_scripts build.bat configure.bat build.sh configure.sh)
file(GLOB entries LIST_DIRECTORIES TRUE "${build_directory}/*")
foreach(entry IN LISTS entries)
  cmake_path(GET entry FILENAME name)
  if(name IN_LIST forwarding_scripts)
    continue()
  endif()
  cmake_path(IS_PREFIX build_directory "${entry}" NORMALIZE is_build_entry)
  if(NOT is_build_entry)
    message(FATAL_ERROR "Cannot remove a path outside the build directory.")
  endif()
  file(REMOVE_RECURSE "${entry}")
  if(EXISTS "${entry}" OR IS_SYMLINK "${entry}")
    message(FATAL_ERROR "Failed to remove ${entry}.")
  endif()
endforeach()
