file(GLOB_RECURSE header_files ${BEAM_INCLUDE_PATH}/Beam/ServicesTests/*.hpp)
file(GLOB_RECURSE source_files ${BEAM_SOURCE_PATH}/ServicesTests/*.cpp)
add_executable(ServicesTests ${header_files} ${source_files})
beam_configure_target(ServicesTests)
set_source_files_properties(${header_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(ServicesTests PUBLIC BeamRoutines)
add_custom_command(TARGET ServicesTests POST_BUILD COMMAND ServicesTests)
beam_install_target(ServicesTests "${TEST_INSTALL_DIRECTORY}")
