cmake_minimum_required(VERSION 3.28)
project(Beam LANGUAGES CXX)
include(Config/project.cmake)
beam_configure_project(
  "${PROJECT_SOURCE_DIR}" "${PROJECT_BINARY_DIR}" ENVIRONMENT BEAM_SKIP_CMAKE=1)
include(Config/dependencies.cmake)
include_directories(${BEAM_INCLUDE_PATH})
include_directories(SYSTEM ${ASPEN_INCLUDE_PATH})
include_directories(SYSTEM ${BOOST_INCLUDE_PATH})
include_directories(SYSTEM ${CRYPTOPP_INCLUDE_PATH})
include_directories(SYSTEM ${DOCTEST_INCLUDE_PATH})
include_directories(SYSTEM ${MYSQL_INCLUDE_PATH})
include_directories(SYSTEM ${OPEN_SSL_INCLUDE_PATH})
include_directories(SYSTEM ${SQLITE_INCLUDE_PATH})
include_directories(SYSTEM ${TCLAP_INCLUDE_PATH})
include_directories(SYSTEM ${VIPER_INCLUDE_PATH})
include_directories(SYSTEM ${YAML_INCLUDE_PATH})
include_directories(SYSTEM ${ZLIB_INCLUDE_PATH})
link_directories(${BOOST_DEBUG_PATH})
link_directories(${BOOST_OPTIMIZED_PATH})
set(TEST_INSTALL_DIRECTORY "${PROJECT_BINARY_DIR}/Tests")
set(LIB_INSTALL_DIRECTORY "${PROJECT_BINARY_DIR}/Libraries")
include(Config/targets.cmake)
add_subdirectory(Config/Beam)
add_subdirectory(Config/Codecs)
add_subdirectory(Config/Collections)
add_subdirectory(Config/IO)
add_subdirectory(Config/Json)
add_subdirectory(Config/Network)
add_subdirectory(Config/Parsers)
add_subdirectory(Config/Pointers)
add_subdirectory(Config/Python)
add_subdirectory(Config/Queries)
add_subdirectory(Config/Queues)
add_subdirectory(Config/Routines)
add_subdirectory(Config/Serialization)
add_subdirectory(Config/ServiceLocator)
add_subdirectory(Config/Services)
add_subdirectory(Config/SignalHandling)
add_subdirectory(Config/Sql)
add_subdirectory(Config/Threading)
add_subdirectory(Config/TimeService)
add_subdirectory(Config/UidService)
add_subdirectory(Config/Utilities)
add_subdirectory(Config/WebServices)
beam_configure_clean()
