file(GLOB_RECURSE source_files ${BEAM_SOURCE_PATH}/UtilitiesTests/*.cpp)
add_executable(UtilitiesTests ${source_files})
beam_configure_target(UtilitiesTests DEPENDENCIES CRYPTOPP YAML)
target_compile_definitions(UtilitiesTests PRIVATE YAML_CPP_STATIC_DEFINE)
target_link_libraries(UtilitiesTests PUBLIC BeamRoutines)
add_custom_command(TARGET UtilitiesTests POST_BUILD COMMAND UtilitiesTests)
beam_install_target(UtilitiesTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
