cmake_minimum_required(VERSION 3.28)
project(ServiceProtocolProfiler LANGUAGES CXX)
include(../../Beam/Config/project.cmake)
beam_configure_project(
  "${PROJECT_SOURCE_DIR}" "${PROJECT_BINARY_DIR}" ENVIRONMENT BEAM_SKIP_CMAKE=1)
include(../../Beam/Config/dependencies.cmake)
include(../../Beam/Config/targets.cmake)
include_directories(${BEAM_INCLUDE_PATH})
link_directories(${BOOST_DEBUG_PATH})
link_directories(${BOOST_OPTIMIZED_PATH})
include_directories(Include)
include_directories("${PROJECT_BINARY_DIR}")
file(GLOB_RECURSE header_files Include/ServiceProtocolProfiler/*.hpp)
list(APPEND header_files "${PROJECT_BINARY_DIR}/Version.hpp")
file(GLOB_RECURSE source_files Source/*.cpp)
add_executable(ServiceProtocolProfiler ${header_files} ${source_files})
beam_configure_target(ServiceProtocolProfiler DEPENDENCIES
  BOOST CRYPTOPP OPEN_SSL OPEN_SSL_BASE TCLAP YAML ZLIB)
target_compile_definitions(ServiceProtocolProfiler PRIVATE
  YAML_CPP_STATIC_DEFINE)
set_source_files_properties(${header_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(ServiceProtocolProfiler PUBLIC BeamRoutines)
if(WIN32)
  target_link_libraries(ServiceProtocolProfiler PUBLIC Crypt32.lib)
endif()
beam_install_target(ServiceProtocolProfiler "${PROJECT_BINARY_DIR}/Application")
install(FILES Application/config.default.yml Application/setup.py
  ../Python/setup_utils.py DESTINATION "${PROJECT_BINARY_DIR}/Application")
if(UNIX)
  install(PROGRAMS Application/check.sh Application/start.sh
    Application/stop.sh DESTINATION "${PROJECT_BINARY_DIR}/Application")
endif()
beam_configure_clean()
