file(GLOB_RECURSE source_files ${BEAM_SOURCE_PATH}/SqlTests/*.cpp)
add_executable(SqlTests ${source_files})
beam_configure_target(SqlTests DEPENDENCIES SQLITE)
target_link_libraries(SqlTests PUBLIC BeamRoutines)
add_custom_command(TARGET SqlTests POST_BUILD COMMAND SqlTests)
beam_install_target(SqlTests "${TEST_INSTALL_DIRECTORY}/$<CONFIG>")
